'use client';
import { FormEvent, useEffect, useState } from 'react';
import { queueAttendance, syncQueued } from '@/lib/offlineQueue';
export default function Kiosk(){const [online,setOnline]=useState(true);const [message,setMessage]=useState('Ready');
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();addEventListener('online',update);addEventListener('offline',update);return()=>{removeEventListener('online',update);removeEventListener('offline',update)}},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const op={schoolId:String(fd.get('schoolId')),deviceId:String(fd.get('deviceId')),studentId:String(fd.get('studentId')),action:String(fd.get('action')) as 'CHECK_IN'|'CHECK_OUT'};if(navigator.onLine){try{const r=await fetch('/api/attendance/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...op,source:'MANUAL',clientEventId:crypto.randomUUID()})});if(!r.ok)throw new Error();setMessage('Attendance saved and parent notification triggered.');return}catch{}}
 await queueAttendance(op);setMessage('Saved offline. It will sync when internet returns.');}
 async function sync(){try{const r=await syncQueued();setMessage(`Synced ${r.synced} offline event(s).`)}catch{setMessage('Sync failed. Events remain safely on this device.')}}
 return <main className="hero" style={{maxWidth:700}}><span className="pill">{online?'● Online':'● Offline mode'}</span><h1 style={{fontSize:38}}>Attendance kiosk</h1><p>Use this screen for a front gate tablet/PC. RFID or QR readers can later fill the Student ID automatically.</p><form className="card" onSubmit={submit}><label>School ID</label><input name="schoolId" required style={{width:'100%',padding:12,margin:'8px 0 12px'}}/><label>Device ID</label><input name="deviceId" defaultValue="front-gate-01" required style={{width:'100%',padding:12,margin:'8px 0 12px'}}/><label>Student ID</label><input name="studentId" required style={{width:'100%',padding:12,margin:'8px 0 12px'}}/><label>Action</label><select name="action" style={{width:'100%',padding:12,margin:'8px 0 16px'}}><option value="CHECK_IN">Check in</option><option value="CHECK_OUT">Check out</option></select><button className="btn">Save attendance</button> <button type="button" className="btn" onClick={sync} style={{marginLeft:8}}>Sync offline events</button><p>{message}</p></form></main>}
